### ISSUE TITLE
Upgrade marked dependency

### ISSUE THREAD

**Issue by netil** [naver/egjs-jsdoc-template#15]
There's a warning of the security vulnerability.
Update `marked` to the latest v0.3.9.

![image](https://user-images.githubusercontent.com/2178435/34599645-d5c80522-f236-11e7-8cb1-19401b7037e9.png)

**Comment by netil** [comment]
jsdoc 3.5.5 should be changed also.
- https://github.com/jsdoc3/jsdoc/issues/1489

**Comment by jongmoon** [comment]
After applying your commit and doing `npm istall`. I found `marked version` is updated to 0.3.9 although I didn't updated jsdoc version.

![image](https://user-images.githubusercontent.com/3255471/34637304-7e330648-f2f6-11e7-8012-75abd5bc3b10.png)

Anyway, jsdoc is currently referenced by grunt-jsdoc not by directly. But grunt-jsdoc version is updated from '1.1.0' (egjs-jsdoc-template) to '2.2.1'(latest grunt-jsdoc) which apply marked 0.3.9 version also. After checking no problem I'll apply latest version.

**Comment by jongmoon** [comment]
grunt-jsdoc 1.1.0 (egjs-jsdoc-template currently use) has caret ranges for jsdoc like follow.

```js
"dependencies": {
    "jsdoc": "^3.4.0"
  },
```

So It does not need to update to grunt-jsdoc 2.2.1. because it will update jsdoc to `latest` if doing `npm i`
  
It looks to be possible to apply marked version to 0.3.9 regardless of jsdoc's marked dependency.

**Comment by jongmoon** [comment]
Despite of this patch, security warning was not solved (in my case.)

Because each egjs project have dependency on `jsdoc`, so... after npm installed, jsdoc still depends on `marked 0.3.7`.

So I think each proejct needs to specify marked version `0.3.9` unless jsdoc patches this.
